apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    tier: frontend
    app: ubuntu
spec:
  selector:
    matchLabels:
      env: production
      type: back-end
  replicas: 2
  template:
    metadata:
      name: ubuntu
      labels:
        env: production
        type: back-end
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["sleep"]
          args: ["180"]