apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      env: production
      type: back-end
  replicas: 4
  template:
    metadata:
      name: nginx
      labels:
        env: production
        type: back-end
    spec:
      containers:
        - name: nginx
          image: nginx
