apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    env: production
spec:
  selector:
    matchLabels:
      env: production
      type: back-end
  replicas: 1
  template:
    metadata:
      name: ubuntu
      labels:
        env: production
        type: back-end
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["sleep"]
          args: ["180"]

