apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    env: production
    type: back-end
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep"]
      args: ["180"]


        

    


    